baseurl: ''
exclude: ['README.md', 'archive/']
permalink: pretty
title: 'Health Shield Logic'

collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

google_analytics_id: UA-167962599-1

plugins:
  - jekyll-environment-variables
  - jekyll-seo-tag
